### PR TITLE
removes unused result and indendation warnings from gcc6.

### PR DESCRIPTION
**Pull request by ghost**
We would like to have the changes because we import it in the OpenFrameworks project.

https://github.com/openframeworks/openFrameworks

### CODE REVIEW

**Comment by mkalten** [comment]
std::ignore seems to be c++11 only, and would therefore render the whole library unusable for earlier versions. is this worth it, just to remove some warnings?

**Comment by ghost** [comment]
Sorry. Does not make any sense in this case to use std::ignore. Did not think about it. My bad.

What about the indentation warning?

**Comment by mkalten** [comment]
sure, we can do the indentation warning ...
you can actually also ignore the read and write return values by placing a (void) in front:

(void) read( breakPipe_[0], &c, 1 );

if that works for you removing the warnings, you could prepare another pull request.

**Comment by ghost** [comment]
gcc 6 does not care about *(void)* unfortunately.

**Comment by mkalten** [comment]
how about static_cast<void>(....); 
???

**Comment by ghost** [comment]
Same story. I tried static_cast<void>. Gcc is kind of a smart ass. ;-)

**Comment by mkalten** [comment]
sorry, that was supposed to be: 
`static_cast<void>(...);`

**Comment by ghost** [comment]
In my version too. Got lost in mark down. ;-)
So to be explicit: does not work either.

**Comment by mkalten** [comment]
if you read the result in a variable,
you would get an unused variable warning though ;)

so, how about just living with that warning?

**Comment by ghost** [comment]
I will try out another solution tomorrow.

**Comment by ghost** [comment]
What about? 

```
template <typename T>
void Unused(T&& /*No name*/) { /*Empty*/ }
```
Then:
```
Unused(read( breakPipe_[0], &c, 1 ));
...
Unused(write( breakPipe_[1], "!", 1 ));
```

**Comment by mkalten** [comment]
buf, also quite a confusing overkill, just to remove a warning?

**Comment by ghost** [comment]
Just a question of compiler warning resistance. I treat warnings as potential errors. I despise them. ;-)

In the end it's your call, Prof.

**Comment by mkalten** [comment]
haha, in this case I would try to submit an according patch to gcc6 to accept the (void) cast ;)

**Comment by ghost** [comment]
LOL! Ok. I will do so.

Have a good evening in Linz or Weimar or where ever you happen to be right now and thanks for your support.

**Comment by mkalten** [comment]
Barcelona actually ... I'll fix the indentation then

**Pull request closed without merging**
